---
- name: copy both public and private ssh keys to root directory
  become: yes
  copy:
      src: "{{ lookup('env','HOME') }}/.ssh/{{ item }}"
      dest: "/root/.ssh/{{ item }}"
      mode: 0600
  with_items:
      - id_rsa
      - id_rsa.pub

- name: Copy instackenv.json to undercloud
  copy:
    src="{{ local_working_dir }}/nodes.json"
    dest="{{ working_dir }}/instackenv.json"

- name: Configure external interface
  become: yes
  shell: >
       ifconfig {{ external_interface }} {{ external_interface_ip }} netmask {{ external_interface_netmask }}

- name: Get mac address of external interface
  shell: >
      ifconfig | grep -n3 {{ external_interface }} | grep -A1 ether | cut -d " " -f 10
  register: mac_addr_external_interface

- name: set-fact for external interface mac address
  set_fact: mac_address_external_interface="{{ mac_addr_external_interface.stdout }}"

- name: Copy template for external interface
  template:
      src: ifcfg-external-interface.j2
      dest: "/etc/sysconfig/network-scripts/ifcfg-{{ external_interface }}"
      mode: 0644

- name: Set MTU values
  become: yes
  shell: >
      ip link set {{ item }} mtu {{ mtu }};
      echo "MTU={{ mtu }}" >> /etc/sysconfig/network-scripts/ifcfg-{{ item }}
  with_items: "{{ mtu_interface }}"

- name: add nameserver to resolv.conf
  become: yes
  lineinfile:
    dest: /etc/resolv.conf
    line: nameserver {{ pvt_nameserver }}
