---
- name: get all the old images IDs
  shell: >
      export OS_AUTH_URL="{{ os_auth_url }}";
      export OS_USERNAME="{{ os_username }}";
      export OS_PASSWORD="{{ os_password }}";
      export OS_TENANT_NAME="{{ os_tenant_name }}";
      glance image-list --sort-key 'created_at' | grep "{{ item }}-undercloud.qcow2" | tail -n +3 | cut -d'|' -f2 | sed 's/ //g'
  register: older_undercloud_image_ids
  with_items: registered_releases

- name: print older images ids
  debug:
      msg: "{{ item }}"
  with_items: "{{ older_undercloud_image_ids.results|map(attribute='stdout_lines')|list }}"

- name: delete the older images
  shell: >
      export OS_AUTH_URL="{{ os_auth_url }}";
      export OS_USERNAME="{{ os_username }}";
      export OS_PASSWORD="{{ os_password }}";
      export OS_TENANT_NAME="{{ os_tenant_name }}";
      glance image-delete {{ item }}
  with_items: "{{ older_undercloud_image_ids.results|map(attribute='stdout_lines')|list }}"
