---
- include: deploy.yml

- name: Validate IPMI and instackenv.json
  hosts: undercloud
  gather_facts: no
  roles:
    - validate-ipmi

- name:  Install the undercloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo/undercloud

- name:  Post undercloud install steps
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo-undercloud-post

- name:  Perpare the baremetal overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - baremetal-overcloud

- name:  Deploy the overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo-overcloud

# Add the overcloud nodes to the generated inventory.
- name:  Inventory the overcloud
  hosts: undercloud
  gather_facts: yes
  vars:
      inventory: all
  roles:
    - tripleo-inventory

- name:  validate the overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo-overcloud-validate
